reboot_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

sleep_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

wake_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

shutdown_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home
